// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VetApp.Data;

#nullable disable

namespace VetApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522204528_AgregarDataSeed")]
    partial class AgregarDataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("VetApp.Models.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("MascotaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VeterinarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MascotaId");

                    b.HasIndex("VeterinarioId");

                    b.ToTable("Citas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fecha = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MascotaId = 1,
                            Motivo = "Revisión general",
                            VeterinarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Fecha = new DateTime(2026, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MascotaId = 2,
                            Motivo = "Vacunación anual",
                            VeterinarioId = 2
                        },
                        new
                        {
                            Id = 3,
                            Fecha = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MascotaId = 3,
                            Motivo = "Control de peso",
                            VeterinarioId = 3
                        });
                });

            modelBuilder.Entity("VetApp.Models.Mascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreDueno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Raza")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mascotas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Especie = "Perro",
                            Nombre = "Max",
                            NombreDueno = "Juan García",
                            Raza = "Labrador"
                        },
                        new
                        {
                            Id = 2,
                            Especie = "Gato",
                            Nombre = "Luna",
                            NombreDueno = "María López",
                            Raza = "Siamés"
                        },
                        new
                        {
                            Id = 3,
                            Especie = "Perro",
                            Nombre = "Rocky",
                            NombreDueno = "Carlos Torres",
                            Raza = "Bulldog"
                        });
                });

            modelBuilder.Entity("VetApp.Models.Veterinario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Veterinarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Especialidad = "Cirugía",
                            Nombre = "Dr. Carlos Ramírez",
                            Telefono = "6641234567"
                        },
                        new
                        {
                            Id = 2,
                            Especialidad = "Dermatología",
                            Nombre = "Dra. Laura Méndez",
                            Telefono = "6649876543"
                        },
                        new
                        {
                            Id = 3,
                            Especialidad = "Nutrición",
                            Nombre = "Dr. Pedro Soto",
                            Telefono = "6645554433"
                        });
                });

            modelBuilder.Entity("VetApp.Models.Cita", b =>
                {
                    b.HasOne("VetApp.Models.Mascota", "Mascota")
                        .WithMany()
                        .HasForeignKey("MascotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VetApp.Models.Veterinario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mascota");

                    b.Navigation("Veterinario");
                });
#pragma warning restore 612, 618
        }
    }
}
